services:
  restate_dev:
    image: docker.restate.dev/restatedev/restate:1.3
    container_name: restate_dev
    ports:
      - "8080:8080"
      - "9070:9070"
      - "9071:9071"
    extra_hosts:
      - "host.docker.internal:host-gateway"
