# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'order-processing-pipeline'
primary_region = 'fra'

[build]
[build.args]
GO_VERSION = "1.24.2"

[env]
RESTATE_PORT = '9080'

[http_service]
internal_port = 9080
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0

[http_service.http_options]
idle_timeout = 10
h2_backend = true

[[vm]]
size = 'shared-cpu-1x'
