# fly.toml app configuration file generated for miltkall-go-playground on 2025-04-11T15:17:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'miltkall-go-playground'
primary_region = 'fra'

[build]

[env]
  RESTATE_PORT = '9080'

[http_service]
  internal_port = 9080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.http_options]
    h2_backend = true
    idle_timeout = 10

[[vm]]
  size = 'shared-cpu-1x'
