[project]
name = "etl"
version = "0.1.0"
description = "Python ETL demo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.3",
    "pytest>=8.3.5",
    "restate-sdk>=0.6.0",
]
