# Default recipe that displays available commands, restate and fly status
[private]
default:
    @just --list
    @echo
    @echo Restate:
    @-restate services status
    @echo
    @echo Fly:
    @-fly status


# Test single email - using virtual net billing template A
[group('test')]
test-email-template-a:
    curl https://${COMPONENTS_RESTATE_HOST}:8080/EmailService/SendEmail \
    -X POST \
    -H "Authorization: Bearer ${COMPONENTS_RESTATE_AUTH_TOKEN}" \
    -H "Content-Type: application/json" \
    -d '{ \
      "from": "info@hellenicvolt.gr", \
      "to": "test@example.com", \
      "template_name": "virtual_net_billing_a", \
      "gemis_company_id": 1234567890, \
      "tag": "marketing" \
    }'
